// Regenerates src/data/enFreq.ts from tmp/freq10000.txt
// Source list: https://github.com/first20hours/google-10000-english (frequency ordered)
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const source = resolve(root, 'tmp/freq10000.txt');
const target = resolve(root, 'src/data/enFreq.ts');
const KEEP = 5000;

const words = readFileSync(source, 'utf8')
  .split(/\r?\n/)
  .map((w) => w.trim().toLowerCase())
  .filter((w) => /^[a-z][a-z'-]*$/.test(w))
  .slice(0, KEEP);

if (words.length < KEEP) throw new Error(`expected ${KEEP} words, got ${words.length}`);

const body = `// AUTO-GENERATED by scripts/gen-freq.mjs -- do not edit by hand.
// Top ${KEEP} English words by corpus frequency (google-10000-english, no swear words).
const RAW = \`${words.join('\n')}\`;

export const EN_FREQ_5000: readonly string[] = RAW.split('\\n').filter(Boolean);

const SET: ReadonlySet<string> = new Set(EN_FREQ_5000);

/** Rank is 1-based; 0 means the word is outside the list. */
export function freqRank(word: string): number {
  const index = EN_FREQ_5000.indexOf(word);
  return index === -1 ? 0 : index + 1;
}

export function inFreqList(word: string): boolean {
  return SET.has(word);
}
`;

mkdirSync(dirname(target), { recursive: true });
writeFileSync(target, body, 'utf8');
console.log(`wrote ${words.length} words -> src/data/enFreq.ts`);
